GUIDE_ITEM_LOCATION_MAP = {
    "Collectable_AbandonedDiary": "Citizen Housing",
    "Collectable_ApartmentMurderReport": "Citizen Apartments",
    "Collectable_BloodPendant": "Citizen Apartments",
    "Collectable_BrokenGoldenCrown": "Citizen Housing",
    "Collectable_Butterfly": "Citizen Apartments",
    "Collectable_CelebratoryGardens": "Gardens",
    "Collectable_Chillies": "Danchi",
    "Collectable_CrimsonAcidPoster": "Syndicate HQ",
    "Collectable_CrystallizedTears": "Citizen Apartments",
    "Collectable_CrystallizedTearsNecklace": "Gardens",
    "Collectable_FallenRose": "Citizen Apartments",
    "Collectable_FishFood": "Danchi",
    "Collectable_Fossil": "Danchi",
    "Collectable_GameCart_Wonton51": "Danchi",
    "Collectable_Grasshopper": "Citizen Apartments",
    "Collectable_Island001": "Gardens",
    "Collectable_Island002": "Gardens",
    "Collectable_Island003": "Council Building",
    "Collectable_Island004": "Beach",
    "Collectable_Island005": "Citizen Housing",
    "Collectable_Island006": "Citizen Housing",
    "Collectable_Island007": "Deep Factory Entrance",
    "Collectable_Island008": "Deep Factory Entrance",
    "Collectable_Island009": "Mountain Gorge",
    "Collectable_Island010": "Agri Fields",
    "Collectable_Island011": "Reality Folding Drive",
    "Collectable_Island012": "Mountain Gorge",
    "Collectable_Island013": "Mountain Gorge",
    "Collectable_Island014": "Opulent Ziggurat",
    "Collectable_Island015": "Citizen Housing",
    "Collectable_Island016": "Dead Zone",
    "Collectable_Island017": "Dead Zone",
    "Collectable_Island018": "Citizen Housing",
    "Collectable_Island019": "Beach",
    "Collectable_Island020": "Mountain Gorge",
    "Collectable_Island021": "Mountain Gorge",
    "Collectable_Island022": "Citizen Housing",
    "Collectable_Island023": "Citizen Housing",
    "Collectable_Island024": "Citizen Apartments",
    "Collectable_Jellyfish": "Beach",
    "Collectable_LDPhoto": "Idle Lands",
    "Collectable_LoversPadlock": "Citizen Apartments",
    "Collectable_LoyaltyCard": "Citizen Housing",
    "Collectable_Loyalty_Levels": "Citizen Housing",
    "Collectable_Luxury_Chocolates": "Syndicate Apartments",
    "Collectable_MaleIdol": "Danchi",
    "Collectable_MessageStones": "Citizen Apartments",
    "Collectable_Music_EmbryonicGreatestHits": "Citizen Housing",
    "Collectable_PainPills": "Citizen Housing",
    "Collectable_Percolator": "Idle Lands",
    "Collectable_PhotoOfMan": "Citizen Apartments",
    "Collectable_PinBadge": "Citizen Apartments",
    "Collectable_PleadingLetter": "Citizen Housing",
    "Collectable_PyramidCharm": "Council Building",
    "Collectable_River_Power_Schedule": "Reality Folding Drive",
    "Collectable_RottenEgg": "Citizen Housing",
    "Collectable_SecretiveCassette": "Citizen Apartments",
    "Collectable_Sequins": "Citizen Housing",
    "Collectable_ShrineCarving_BeautifulSpectre": "Opulent Ziggurat",
    "Collectable_ShrineCarving_BloodDancer": "Deep Factory Entrance",
    "Collectable_ShrineCarving_CosmicDeceit": "Citizen Housing",
    "Collectable_ShrineCarving_CryingGrudge": "Danchi",
    "Collectable_ShrineCarving_DamnedHarmony": "Syndicate HQ",
    "Collectable_ShrineCarving_DestroyedEden": "Opulent Ziggurat",
    "Collectable_ShrineCarving_DireRose": "Deep Factory Entrance",
    "Collectable_ShrineCarving_DyingFromSadness": "Dead Zone",
    "Collectable_ShrineCarving_EnchantedBlue": "Citizen Apartments",
    "Collectable_ShrineCarving_EndlessMoon": "Citizen Housing",
    "Collectable_ShrineCarving_LostPain": "Beach",
    "Collectable_ShrineCarving_MoonlightPetal": "Opulent Ziggurat",
    "Collectable_ShrineCarving_NewNight": "Marshal Barracks",
    "Collectable_ShrineCarving_NightmareRevival": "Citizen Housing",
    "Collectable_ShrineCarving_ShadowZero": "Opulent Ziggurat",
    "Collectable_ShrineCarving_SilentGoat": "Citizen Apartments",
    "Collectable_ShrineCarving_VileEmbrace": "Opulent Ziggurat",
    "Collectable_SilentTowerCarving": "Council Building",
    "Collectable_Stones": "Beach",
    "Collectable_Tea": "Syndicate Apartments",
    "Collectable_Transmission_001": "Mountain Gorge",
    "Collectable_Transmission_002": "Mountain Gorge",
    "Collectable_Transmission_003": "Deep Factory Entrance",
    "Collectable_Transmission_004": "Agri Fields",
    "Collectable_Transmission_005": "Beach",
    "Collectable_WorshipStamp": "Opulent Ziggurat",
    "Collectable_alarmclock": "Citizen Housing",
    "Collectable_mushroom": "Syndicate Apartments",
    "Collectable_pistachios": "Danchi",
    "Collectable_secateurs": "Syndicate Apartments",
    "Collectable_videotape": "Citizen Apartments",
    "Collectable_wellreadbook": "Idle Lands",
    "Dog_treat": "Citizen Housing",
    "Factory_EmployeeCard": "Deep Factory Entrance",
    "SoundTrack_8thStreetRose": "Citizen Housing",
    "SoundTrack_AboutThat": "K.HX's Workshop",
    "SoundTrack_DontMisunderstand": "Reality Folding Drive",
    "SoundTrack_EGO24": "Citizen Apartments",
    "SoundTrack_EndOfTheWorld": "Syndicate HQ",
    "SoundTrack_GOGOSTYLE": "Agri Fields",
    "SoundTrack_HeadlightsOnTheShore": "Beach",
    "SoundTrack_HouseOfBliss": "Citizen Housing",
    "SoundTrack_LadyBlue_Vaporwave_Ver": "Citizen Apartments",
    "SoundTrack_LastDanceXX": "Citizen Apartments",
    "SoundTrack_Leaving": "Syndicate HQ",
    "SoundTrack_MidoriEyes": "Mountain Gorge",
    "SoundTrack_SunsetSong": "Citizen Apartments",
    "SoundTrack_TheLemegetonBop": "Danchi",
    "SoundTrack_ToTheHeart": "Council Building",
    "SoundTrack_UnlimitedLuv": "Danchi",
    "Whisky_001": "Paradise Gates",
    "Whisky_002": "Council Building",
    "Whisky_003": "Citizen Apartments",
    "Whisky_004": "Citizen Housing",
    "Whisky_005": "Citizen Housing",
    "Whisky_006": "Citizen Housing",
    "Whisky_007": "Dead Zone",
    "Whisky_008": "Danchi",
    "Whisky_009": "Beach",
    "Whisky_010": "Mountain Gorge",
    "Whisky_011": "K.HX's Workshop",
    "Whisky_012": "Agri Fields",
    "phonecharm_crimson": "Citizen Apartments",
    "phonecharm_deadnebula": "Citizen Housing",
    "phonecharm_tamago": "Danchi"
}
